In [4]:
import torch
import torch.nn as nn

# вход: (batch, seq_len, features)
# вход: (students_count, semesters, marks)
x = torch.randn(1, 2, 15)

In [5]:
x

tensor([[[ 1.2534, -0.1454, -0.0590, -0.8603,  0.0467,  0.5878, -0.0702,
           0.4417, -1.2915,  1.2849,  0.0365, -0.3520, -0.0576, -0.6589,
          -1.1868],
         [-1.1958,  1.0573,  1.7484,  1.0201,  1.3809, -0.4833,  1.3611,
          -1.2225, -0.7127,  0.5285, -0.8980,  0.1316, -0.3407, -0.7943,
          -0.6166]]])

In [8]:
rnn = nn.RNN(input_size=15, hidden_size=8, batch_first=True)

In [10]:
rnn.state_dict()

OrderedDict([('weight_ih_l0',
              tensor([[ 0.2273,  0.2495,  0.0423,  0.0505,  0.0853,  0.1201, -0.0560, -0.2125,
                       -0.1868,  0.2171, -0.1284,  0.0449,  0.3440,  0.0906,  0.1750],
                      [-0.1609,  0.1279, -0.0813, -0.0410, -0.1835, -0.3179,  0.0144, -0.2710,
                       -0.1847, -0.0269,  0.3148,  0.2327,  0.3385,  0.1811,  0.2240],
                      [ 0.2549, -0.3255, -0.3112, -0.0462,  0.2716,  0.1669,  0.0626,  0.2948,
                        0.2268, -0.3034,  0.2131,  0.2642,  0.1200, -0.0681, -0.1765],
                      [ 0.0007, -0.1051,  0.2671, -0.2822,  0.3007,  0.0026, -0.0882,  0.1382,
                        0.0263, -0.1677, -0.1942,  0.1345,  0.0728, -0.2099,  0.1386],
                      [-0.0908, -0.0612,  0.1996, -0.3214, -0.2442, -0.2797, -0.1721, -0.1544,
                        0.0922,  0.2797, -0.0339, -0.1049, -0.0568, -0.2562, -0.0951],
                      [-0.3271,  0.2330, -0.2276,  0.2526,  

In [11]:
output, h = rnn(x)

In [12]:
h

tensor([[[ 0.6614, -0.3555, -0.9208,  0.0968,  0.6592, -0.3735, -0.5084,
          -0.9469]]], grad_fn=<StackBackward0>)

In [13]:
output

tensor([[[ 0.6335, -0.6453, -0.0731, -0.1753,  0.3695, -0.9242, -0.7409,
           0.2452],
         [ 0.6614, -0.3555, -0.9208,  0.0968,  0.6592, -0.3735, -0.5084,
          -0.9469]]], grad_fn=<TransposeBackward1>)

In [14]:
print(output.shape)  # (1, 2, 8)
print(h.shape)  # (1, 1, 8)

torch.Size([1, 2, 8])
torch.Size([1, 1, 8])


In [15]:
lstm = nn.LSTM(input_size=15, hidden_size=8, batch_first=True)
output, (h, c) = lstm(x)

In [16]:
output

tensor([[[-0.0352,  0.0121,  0.0510, -0.0799,  0.0857,  0.2816,  0.3041,
          -0.0409],
         [-0.0692,  0.2263, -0.0168, -0.1961,  0.1481,  0.1914,  0.3409,
          -0.0062]]], grad_fn=<TransposeBackward0>)

In [17]:
h

tensor([[[-0.0692,  0.2263, -0.0168, -0.1961,  0.1481,  0.1914,  0.3409,
          -0.0062]]], grad_fn=<StackBackward0>)

In [18]:
c

tensor([[[-0.4455,  0.6850, -0.0242, -0.3330,  0.4138,  0.2302,  0.5898,
          -0.0285]]], grad_fn=<StackBackward0>)

In [21]:
apple = 1
banana = 2
orange = 3

In [28]:
a = [1, 0, 0, 0, 0, 0, 0, 0, 0]
b = [0, 1, 0, 0, 0, 0, 0, 0, 0]
c = [0, 0, 1, 0, 0, 0, 0, 0, 0]

In [29]:
print(output.shape)  # (1, 2, 8)
print(h.shape)  # (1, 1, 8)

torch.Size([1, 2, 8])
torch.Size([1, 1, 8])


In [30]:
vocab = {"I": 0, "love": 1, "AI": 2}
sentence = ["I", "love", "AI"]
x = torch.tensor([vocab[w] for w in sentence])

In [36]:
vocab

{'I': 0, 'love': 1, 'AI': 2}

In [37]:
x

tensor([0, 1, 2])

In [41]:
first = (" ".join(sentence)).split(" ")[1]

In [42]:
first

'love'

In [40]:
vocab[first]

1

In [43]:
embedding = nn.Embedding(3, 9)

In [44]:
print(embedding(x[2]))

tensor([ 0.1171, -0.3256,  0.5871,  0.0951,  0.9583,  0.3649,  2.2973, -1.3532,
         0.4088], grad_fn=<EmbeddingBackward0>)
